Repository bird-house/twitcher, pull requests merged in 2019-05, with the labels that each got.

#60 fixed uuid on py3
  twitcher/tokengenerator.py
Labels: bug

#61 skip python 2.7 support
  .travis.yml
  Makefile
  buildout.cfg
  environment.yml
  requirements.txt
  tests/test_utils.py
  twitcher/client.py
  twitcher/owsproxy.py
  twitcher/owsrequest.py
  twitcher/store/memory.py
  twitcher/tokengenerator.py
  twitcher/utils.py
Labels: enhancement

#62 Fix py3 encoding
  tests/test_owsrequest_wps.py
  twitcher/client.py
  twitcher/owsproxy.py
  twitcher/owsrequest.py
  twitcher/twitcherctl.py
Labels: bug

#63 skip buildout
  .gitignore
  .travis.yml
  Makefile
  Makefile.config.example
  README.rst
  bootstrap.sh
  buildout.cfg
  custom.cfg.example
  development.ini
  docs/Makefile
  docs/source/_static/README.txt
  docs/source/_static/birdhouse_logo.svg
  docs/source/_static/favicon.ico
  docs/source/api.rst
  docs/source/appendix.rst
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/dev_guide.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/overview.rst
  docs/source/running.rst
  docs/source/tutorial.rst
  environment.yml
  etc/mongod.conf
  etc/nginx.conf
  readthedocs.yml
  requirements.txt
  requirements_dev.txt
  requirements_rtd.txt
  setup.cfg
  setup.py
  spec-file.txt
  templates/twitcher.ini
  tests/functional/common.py
  tests/test_datatype.py
  tests/test_owsrequest_wms.py
  tests/test_owsrequest_wps.py
  tests/test_owssecurity.py
  tests/test_utils.py
  twitcher/__init__.py
  twitcher/__version__.py
  twitcher/db.py
  twitcher/owsproxy.py
  twitcher/rpcinterface.py
  twitcher/twitcherctl.py
Labels: enhancement

#65 added "make db"
  Makefile
  docs/source/installation.rst
  twitcher/scripts/initialize_db.py
Labels: enhancement

#67 Adapter and Docker
  .dockerignore
  .gitignore
  AUTHORS.rst
  CHANGES.rst
  Dockerfile
  Makefile
  development.ini
  requirements.txt
  requirements_dev.txt
  setup.cfg
  setup.py
  tests/test_adapter.py
  tests/test_owsproxy.py
  twitcher/adapter/__init__.py
  twitcher/adapter/base.py
  twitcher/adapter/default.py
  twitcher/frontpage.py
  twitcher/owsproxy.py
  twitcher/owssecurity.py
  twitcher/rpcinterface.py
  twitcher/store.py
  twitcher/tweens.py
  twitcher/typedefs.py
  twitcher/utils.py
Labels: enhancement

#70 removed unused config module
  development.ini
  twitcher/__init__.py
  twitcher/config.py
  twitcher/owsproxy.py
  twitcher/rpcinterface.py
Labels: enhancement

#71 fix datatype for boolean values
  twitcher/datatype.py
  twitcher/store.py
Labels: bug

#72 Fix service store insert or update
  tests/test_store.py
  twitcher/store.py
Labels: bug

#73 don't lose config if provided directly (#69)
  twitcher/adapter/base.py
  twitcher/adapter/default.py
Labels: bug

#74 using asbool
  twitcher/datatype.py
Labels: enhancement

#75 simplified makefile, skipped conda
  .travis.yml
  Makefile
  docs/source/dev_guide.rst
  docs/source/installation.rst
  requirements_dev.txt
  setup.cfg
  setup.py
  spec-file.txt
Labels: enhancement

#77 Import adapter
  CHANGES.rst
  Makefile
  requirements.txt
  setup.cfg
  setup.py
  tests/test_adapter.py
  twitcher/__init__.py
  twitcher/adapter/__init__.py
  twitcher/adapter/base.py
  twitcher/adapter/default.py
Labels: bug, enhancement
